title: Prakhar Rakhya
logo: /assets/images/photo_circle.jpg
description: I'm an ML/DL engineer specializing in end-to-end pipelines, dedicated to researching and implementing new model architectures for cutting-edge solutions.
#show_downloads: true
theme: jekyll-theme-minimal
